
// lib/class-features.ts

export interface ClassFeature {
    name: string;
    description: string;
    isChoice?: boolean;
    choiceText?: string;
}

export interface LevelProgression {
    features: ClassFeature[];
    hitDice?: string;
    hpIncrease?: string;
}

const ASI: ClassFeature = { name: "Melhoria no Valor de Atributo", description: "Aumento de Atributo ou Talento.", isChoice: true };

export const CLASS_PROGRESSION: Record<string, Record<number, LevelProgression>> = {
    "Bárbaro": {
        1: { features: [{ name: "Fúria", description: "Vantagem em testes de Força, bônus no dano e resistência a danos físicos." }, { name: "Defesa Sem Armadura", description: "CA = 10 + Destreza + Constituição." }], hitDice: "1d12" },
        2: { features: [{ name: "Ataque Temerário", description: "Vantagem em ataques, mas ataques contra você também têm vantagem." }, { name: "Sentido de Perigo", description: "Vantagem em salvaguardas de Destreza." }] },
        3: { features: [{ name: "Caminho Primitivo", description: "Escolha sua trilha de fúria.", isChoice: true }] },
        4: { features: [ASI] },
        5: { features: [{ name: "Ataque Extra", description: "Pode atacar duas vezes." }, { name: "Movimento Rápido", description: "Deslocamento aumenta em 3 metros." }] },
        6: { features: [{ name: "Recurso de Caminho Primitivo", description: "Habilidade baseada na sua subclasse." }] },
        7: { features: [{ name: "Instinto Selvagem", description: "Vantagem em Iniciativa." }] },
        8: { features: [ASI] },
        9: { features: [{ name: "Crítico Brutal (1 dado)", description: "Role um dado extra de dano em acertos críticos." }] },
        10: { features: [{ name: "Recurso de Caminho Primitivo", description: "Habilidade baseada na sua subclasse." }] },
        11: { features: [{ name: "Fúria Implacável", description: "Pode persistir lutando mesmo com 0 PV." }] },
        12: { features: [ASI] },
        13: { features: [{ name: "Crítico Brutal (2 dados)", description: "Role dois dados extras de dano em acertos críticos." }] },
        14: { features: [{ name: "Recurso de Caminho Primitivo", description: "Habilidade baseada na sua subclasse." }] },
        15: { features: [{ name: "Fúria Persistente", description: "Sua fúria só termina se você cair inconsciente ou encerrá-la." }] },
        16: { features: [ASI] },
        17: { features: [{ name: "Crítico Brutal (3 dados)", description: "Role três dados extras de dano em acertos críticos." }] },
        18: { features: [{ name: "Força Indomável", description: "Seu teste de Força não pode ser menor que seu valor base de Força." }] },
        19: { features: [ASI] },
        20: { features: [{ name: "Campeão Primal", description: "Sua Força e Constituição aumentam em 4, até o máximo de 24!" }] }
    },
    "Bardo": {
        1: { features: [{ name: "Inspiração Bárdica (d6)", description: "Ajude aliados com dados de bônus." }, { name: "Conjuração", description: "Lance magias através da música ou oratória." }], hitDice: "1d8" },
        2: { features: [{ name: "Pau para Toda Obra", description: "Bônus em perícias nâo proficientes." }, { name: "Canção de Descanso (d6)", description: "Aumenta cura em descansos curtos." }] },
        3: { features: [{ name: "Colégio Bárdico", description: "Escolha sua especialização.", isChoice: true }, { name: "Especialização", description: "Dobre bônus em 2 perícias.", isChoice: true }] },
        4: { features: [ASI] },
        5: { features: [{ name: "Fonte de Inspiração", description: "Recupera Inspiração Bárdica em descansos curtos." }, { name: "Inspiração Bárdica (d8)", description: "Dado aumenta para d8." }] },
        6: { features: [{ name: "Recurso de Colégio Bárdico", description: "Habilidade de subclasse." }, { name: "Contra-encanto", description: "Use música para proteger aliados de medo ou encanto." }] },
        7: { features: [{ name: "Magias de 4º Nível", description: "Acesso a magias mais poderosas." }] },
        8: { features: [ASI] },
        9: { features: [{ name: "Canção de Descanso (d8)", description: "Cura aumentada para d8." }] },
        10: { features: [{ name: "Inspiração Bárdica (d10)", description: "Dado aumenta para d10." }, { name: "Segredos Mágicos", description: "Aprenda magias de outras classes!", isChoice: true }, { name: "Especialização", description: "Mais 2 perícias com bônus dobrado.", isChoice: true }] },
        11: { features: [{ name: "Magias de 6º Nível", description: "Acesso a segredos arcanos superiores." }] },
        12: { features: [ASI] },
        13: { features: [{ name: "Canção de Descanso (d10)", description: "Cura aumentada para d10." }] },
        14: { features: [{ name: "Recurso de Colégio Bárdico", description: "Habilidade de subclasse final." }, { name: "Segredos Mágicos", description: "Mais 2 magias de qualquer classe.", isChoice: true }] },
        15: { features: [{ name: "Inspiração Bárdica (d12)", description: "Dado aumenta para d12." }] },
        16: { features: [ASI] },
        17: { features: [{ name: "Canção de Descanso (d12)", description: "Cura máxima em descansos." }] },
        18: { features: [{ name: "Segredos Mágicos", description: "Última seleção de magias externas.", isChoice: true }] },
        19: { features: [ASI] },
        20: { features: [{ name: "Inspiração Superior", description: "Se não tiver Inspiração ao iniciar o combate, recupera um dado." }] }
    },
    "Clérigo": {
        1: { features: [{ name: "Domínio Divino", description: "Escolha o domínio do seu deus.", isChoice: true }, { name: "Conjuração", description: "Canalize o poder dos deuses." }], hitDice: "1d8" },
        2: { features: [{ name: "Canalizar Divindade (1/uso)", description: "Use energia divina para efeitos especiais." }] },
        3: { features: [{ name: "Magias de 2º Nível", description: "Acesso a milagres maiores." }] },
        4: { features: [ASI] },
        5: { features: [{ name: "Destruir Mortos-Vivos (ND 1/2)", description: "Expulse e destrua criaturas profanas." }] },
        6: { features: [{ name: "Canalizar Divindade (2/usos)", description: "Mais frequencia de poder divino." }, { name: "Recurso de Domínio", description: "Habilidade de subclasse." }] },
        7: { features: [{ name: "Magias de 4º Nível", description: "Milagres de grande escala." }] },
        8: { features: [ASI], hpIncrease: "Potencializa seus ataques ou magias." },
        9: { features: [{ name: "Magias de 5º Nível", description: "Milagres supremos." }] },
        10: { features: [{ name: "Intervenção Divina", description: "Peça ajuda direta ao seu deus (porcentagem de chance)." }] },
        11: { features: [{ name: "Destruir Mortos-Vivos (ND 2)", description: "Destrua mortos-vivos mais fortes." }] },
        12: { features: [ASI] },
        13: { features: [{ name: "Magias de 7º Nível", description: "Poder sagrado avassalador." }] },
        14: { features: [{ name: "Destruir Mortos-Vivos (ND 3)", description: "Poder de purificação aumentado." }] },
        15: { features: [{ name: "Magias de 8º Nível", description: "Milagres lendários." }] },
        16: { features: [ASI] },
        17: { features: [{ name: "Destruir Mortos-Vivos (ND 4)", description: "Mestre da purificação." }, { name: "Recurso de Domínio", description: "Poder final da subclasse." }] },
        18: { features: [{ name: "Canalizar Divindade (3/usos)", description: "Poder divino quase constante." }] },
        19: { features: [ASI] },
        20: { features: [{ name: "Intervenção Divina Garantida", description: "Seu deus agora responde SEMPRE ao seu chamado!" }] }
    },
    "Druida": {
        1: { features: [{ name: "Druídico", description: "O idioma secreto da natureza." }, { name: "Conjuração", description: "Manipule as forças da natureza." }], hitDice: "1d8" },
        2: { features: [{ name: "Forma Selvagem", description: "Transforme-se em animais." }, { name: "Círculo Druídico", description: "Escolha seu círculo sagrado.", isChoice: true }] },
        3: { features: [{ name: "Magias de 2º Nível", description: "Acesso a magias naturais mais fortes." }] },
        4: { features: [ASI], hpIncrease: "Forma Selvagem melhorada (ND 1/2, sem voo)." },
        5: { features: [{ name: "Magias de 3º Nível", description: "Comande o clima e as plantas." }] },
        6: { features: [{ name: "Recurso de Círculo Druídico", description: "Habilidade de subclasse." }] },
        7: { features: [{ name: "Magias de 4º Nível", description: "Acesso a grandes magias naturais." }] },
        8: { features: [ASI], hpIncrease: "Forma Selvagem melhorada (ND 1, com voo)." },
        9: { features: [{ name: "Magias de 5º Nível", description: "Fale com o próprio mundo." }] },
        10: { features: [{ name: "Recurso de Círculo Druídico", description: "Habilidade de subclasse superior." }] },
        11: { features: [{ name: "Magias de 6º Nível", description: "Poder natural devastador." }] },
        12: { features: [ASI] },
        13: { features: [{ name: "Magias de 7º Nível", description: "Acesso a eras antigas da natureza." }] },
        14: { features: [{ name: "Recurso de Círculo Druídico", description: "Poder final da natureza." }] },
        15: { features: [{ name: "Magias de 8º Nível", description: "Regência sobre o bioma." }] },
        16: { features: [ASI] },
        17: { features: [{ name: "Magias de 9º Nível", description: "Avatar da natureza." }] },
        18: { features: [{ name: "Corpo Atemporal", description: "Envelhece 10 anos a cada 100!" }, { name: "Magias de Fera", description: "Lance magias enquanto estiver em Forma Selvagem." }] },
        19: { features: [ASI] },
        20: { features: [{ name: "Arquidruida", description: "Uso de Forma Selvagem ILIMITADO e ignora componentes verbais/somáticos!" }] }
    },
    "Guerreiro": {
        1: { features: [{ name: "Estilo de Luta", description: "Sua especialidade marcial.", isChoice: true }, { name: "Retomada de Fôlego", description: "Cura rápida em combate." }], hitDice: "1d10" },
        2: { features: [{ name: "Surto de Ação (1/uso)", description: "Ação extra no turno." }] },
        3: { features: [{ name: "Arquétipo Marcial", description: "Escolha sua especialidade.", isChoice: true }] },
        4: { features: [ASI] },
        5: { features: [{ name: "Ataque Extra (1)", description: "Dois ataques por ação." }] },
        6: { features: [ASI] },
        7: { features: [{ name: "Recurso de Arquétipo", description: "Habilidade de subclasse." }] },
        8: { features: [ASI] },
        9: { features: [{ name: "Indomável (1/uso)", description: "Role novamente uma salvaguarda falha." }] },
        10: { features: [{ name: "Recurso de Arquétipo", description: "Habilidade marcante da subclasse." }] },
        11: { features: [{ name: "Ataque Extra (2)", description: "Três ataques por ação!" }] },
        12: { features: [ASI] },
        13: { features: [{ name: "Indomável (2/usos)", description: "Mais resiliência mental e física." }] },
        14: { features: [ASI] },
        15: { features: [{ name: "Recurso de Arquétipo", description: "Poder avançado da subclasse." }] },
        16: { features: [ASI] },
        17: { features: [{ name: "Surto de Ação (2/usos)", description: "Duas vezes a ação extra.", choiceText: "Não no mesmo turno." }, { name: "Indomável (3/usos)", description: "Coração de aço." }] },
        18: { features: [{ name: "Recurso de Arquétipo", description: "Poder final da subclasse." }] },
        19: { features: [ASI] },
        20: { features: [{ name: "Ataque Extra (3)", description: "QUATRO ataques em uma única ação! O terror dos campos de batalha." }] }
    },
    "Ladino": {
        1: { features: [{ name: "Ataque Furtivo (1d6)", description: "Dano extra em alvos vulneráveis." }, { name: "Especialização", description: "Foco extremo em 2 perícias.", isChoice: true }, { name: "Gíria de Ladrão", description: "Linguagem secreta do submundo." }], hitDice: "1d8" },
        2: { features: [{ name: "Ação Astuta", description: "Corre, Desengaja ou Esconde como Bônus." }] },
        3: { features: [{ name: "Arquétipo de Ladino", description: "Escolha sua especialidade.", isChoice: true }, { name: "Ataque Furtivo (2d6)", description: "Dano aumentado." }] },
        4: { features: [ASI] },
        5: { features: [{ name: "Esquiva Sobrenatural", description: "Reduza dano de ataques pela metade usando Reação." }, { name: "Ataque Furtivo (3d6)", description: "Dano aumentado." }] },
        6: { features: [{ name: "Especialização", description: "Mais 2 perícias com bônus dobrado.", isChoice: true }] },
        7: { features: [{ name: "Evasão", description: "Dano zero em salvaguardas de Destreza bem-sucedidas." }, { name: "Ataque Furtivo (4d6)", description: "Dano aumentado." }] },
        8: { features: [ASI] },
        9: { features: [{ name: "Recurso de Arquétipo", description: "Habilidade de subclasse." }, { name: "Ataque Furtivo (5d6)", description: "Dano aumentado." }] },
        10: { features: [ASI] },
        11: { features: [{ name: "Talento Confiável", description: "Suas rolagens de perícias (proficientes) nunca são menores que 10 no dado.", choiceText: "Transforma qualquer resultado 1-9 em 10." }, { name: "Ataque Furtivo (6d6)", description: "Dano aumentado." }] },
        12: { features: [ASI] },
        13: { features: [{ name: "Recurso de Arquétipo", description: "Habilidade superior de subclasse." }, { name: "Ataque Furtivo (7d6)", description: "Dano aumentado." }] },
        14: { features: [{ name: "Sentido Cego", description: "Perceba criaturas escondidas a 3 metros." }] },
        15: { features: [{ name: "Mente Escorregadia", description: "Proficiência em testes de Sabedoria." }, { name: "Ataque Furtivo (8d6)", description: "Dano aumentado." }] },
        16: { features: [ASI] },
        17: { features: [{ name: "Recurso de Arquétipo", description: "Habilidade final de subclasse." }, { name: "Ataque Furtivo (9d6)", description: "Dano aumentado." }] },
        18: { features: [{ name: "Evasivo", description: "Ataques contra você não têm vantagem se você não estiver incapacitado." }] },
        19: { features: [ASI], hpIncrease: "Ataque Furtivo (10d6)" },
        20: { features: [{ name: "Golpe de Sorte", description: "Transforme uma falha em sucesso natural (1/descanso curto)." }] }
    },
    "Monge": {
        1: { features: [{ name: "Defesa Sem Armadura", description: "CA = 10 + Destreza + Sabedoria." }, { name: "Artes Marciais (d4)", description: "Bônus para ataques desarmados." }], hitDice: "1d8" },
        2: { features: [{ name: "Ki", description: "Energia mística para Rajada de Golpes, Defesa Paciente e Passo do Vento." }, { name: "Movimento Sem Armadura (+3m)", description: "Velocidade aumentada." }] },
        3: { features: [{ name: "Tradição Monástica", description: "Escolha seu monastério.", isChoice: true }, { name: "Defletir Projéteis", description: "Pegue ou desvie flechas." }] },
        4: { features: [ASI], hpIncrease: "Queda Suave (Dano reduzido: 5x nível de monge)." },
        5: { features: [{ name: "Ataque Extra", description: "Dois ataques por ação." }, { name: "Ataque Atordoante", description: "Gaste Ki para atordoar alvos." }, { name: "Artes Marciais (d6)", description: "Dano aumentado." }] },
        6: { features: [{ name: "Golpes de Ki", description: "Seus ataques desarmados contam como mágicos." }, { name: "Movimento Sem Armadura (+4,5m)", description: "Velocidade aumentada." }] },
        7: { features: [{ name: "Evasão", description: "Evite dano de áreas de efeito." }, { name: "Tranquilidade de Mente", description: "Encerre efeitos de medo ou encanto em si mesmo." }] },
        8: { features: [ASI] },
        9: { features: [{ name: "Passo das Nuvens", description: "Pode correr por superfícies líquidas e paredes." }, { name: "Movimento Sem Armadura (+6m)", description: "Velocidade aumentada." }] },
        10: { features: [{ name: "Pureza de Corpo", description: "Imunidade a doenças e venenos." }, { name: "Artes Marciais (d8)", description: "Dano aumentado." }] },
        11: { features: [{ name: "Recurso de Tradição", description: "Habilidade superior de monge." }] },
        12: { features: [ASI] },
        13: { features: [{ name: "Língua do Sol e da Lua", description: "Entenda e fale todos os idiomas." }] },
        14: { features: [{ name: "Alma Diamantina", description: "Proficiência em TODAS as salvaguardas!" }, { name: "Movimento Sem Armadura (+7,5m)", description: "Velocidade aumentada." }] },
        15: { features: [{ name: "Corpo Atemporal", description: "Não sofre efeitos da velhice e não precisa comer/beber." }] },
        16: { features: [ASI] },
        17: { features: [{ name: "Recurso de Tradição", description: "Mestria final da subclasse." }, { name: "Artes Marciais (d10)", description: "Dano aumentado." }] },
        18: { features: [{ name: "Corpo Vazio", description: "Invisibilidade e projeção astral usando Ki." }, { name: "Movimento Sem Armadura (+9m)", description: "Velocidade aumentada." }] },
        19: { features: [ASI] },
        20: { features: [{ name: "Auto-perfeição", description: "Se não tiver Ki ao iniciar combate, recupera 4 pontos de Ki." }] }
    },
    "Paladino": {
        1: { features: [{ name: "Sentido Divino", description: "Detecte seres celestiais, fiéis ou mortos-vivos." }, { name: "Mãos Curadoras", description: "Cure feridas com seu toque (5x nível)." }], hitDice: "1d10" },
        2: { features: [{ name: "Estilo de Luta", description: "Sua especialidade defensiva ou ofensiva.", isChoice: true }, { name: "Conjuração", description: "Lance magias de paladino." }, { name: "Destruição Divina", description: "Converta magias em dano radiante extra!" }] },
        3: { features: [{ name: "Saúde Divina", description: "Imunidade a doenças." }, { name: "Juramento Sagrado", description: "Sua subclasse e dever.", isChoice: true }] },
        4: { features: [ASI] },
        5: { features: [{ name: "Ataque Extra", description: "Dois ataques por ação." }] },
        6: { features: [{ name: "Aura de Proteção", description: "Bônus de Carisma para salvaguardas de aliados próximos (3m)." }] },
        7: { features: [{ name: "Recurso de Juramento", description: "Habilidade de aura da subclasse." }] },
        8: { features: [ASI] },
        9: { features: [{ name: "Magias de 3º Nível", description: "Acesso a poderes sagrados superiores." }] },
        10: { features: [{ name: "Aura de Coragem", description: "Aliados próximos não podem ser amedrontados." }] },
        11: { features: [{ name: "Destruição Divina Aprimorada", description: "Seus ataques causam +1d8 radiante SEMPRE." }] },
        12: { features: [ASI] },
        13: { features: [{ name: "Magias de 4º Nível", description: "Poder de campeão divino." }] },
        14: { features: [{ name: "Toque Purificador", description: "Use sua ação para encerrar magias em você ou aliados." }] },
        15: { features: [{ name: "Recurso de Juramento", description: "Habilidade avançada da subclasse." }] },
        16: { features: [ASI] },
        17: { features: [{ name: "Magias de 5º Nível", description: "O ápice do poder sagrado." }] },
        18: { features: [{ name: "Melhoria de Áura", description: "O alcance de todas as suas auras aumenta para 9 metros!" }] },
        19: { features: [ASI] },
        20: { features: [{ name: "Avatar Sagrado", description: "Forma final baseada no seu juramento (1/dia).", isChoice: true }] }
    },
    "Patrulheiro": {
        1: { features: [{ name: "Inimigo Favorito", description: "Bônus contra tipos específicos de criaturas.", isChoice: true }, { name: "Explorador Natural", description: "Vantagem em terrenos específicos.", isChoice: true }], hitDice: "1d10" },
        2: { features: [{ name: "Estilo de Luta", description: "Arqueiro, Duelista, etc.", isChoice: true }, { name: "Conjuração", description: "Lance magias de patrulheiro." }] },
        3: { features: [{ name: "Arquétipo de Patrulheiro", description: "Escolha sua especialidade.", isChoice: true }, { name: "Prontidão Primal", description: "Detecte criaturas a quilômetros." }] },
        4: { features: [ASI] },
        5: { features: [{ name: "Ataque Extra", description: "Dois ataques por ação." }] },
        6: { features: [{ name: "Melhoria de Inimigo/Explorador", description: "Escolha novos tipos.", isChoice: true }] },
        7: { features: [{ name: "Recurso de Arquétipo", description: "Habilidade de subclasse." }] },
        8: { features: [ASI], hpIncrease: "Caminhar na Terra (Ignore terreno difícil não mágico)." },
        9: { features: [{ name: "Magias de 3º Nível", description: "Acesso a domínios da natureza." }] },
        10: { features: [{ name: "Desaparecer", description: "Pode usar Esconder-se como ação bônus." }, { name: "Camuflagem na Natureza", description: "Crie disfarces de lama e folhagem." }] },
        11: { features: [{ name: "Recurso de Arquétipo", description: "Poder superior da subclasse." }] },
        12: { features: [ASI] },
        13: { features: [{ name: "Magias de 4º Nível", description: "Poder de caçador supremo." }] },
        14: { features: [{ name: "Melhoria de Inimigo/Explorador", description: "Escolha novos tipos.", isChoice: true }, { name: "Sentido Desvanecente", description: "Vantagem em Testes de Sobrevivência contra rastros." }] },
        15: { features: [{ name: "Recurso de Arquétipo", description: "Mestria final da subclasse." }] },
        16: { features: [ASI] },
        17: { features: [{ name: "Magias de 5º Nível", description: "O ápice do patrulheiro." }] },
        18: { features: [{ name: "Sentidos Selvagens", description: "Lute perfeitamente contra alvos que não consegue ver." }] },
        19: { features: [ASI] },
        20: { features: [{ name: "Matador de Inimigos", description: "Adicione modificador de Sabedoria ao dano contra seus Inimigos Favoritos!" }] }
    },
    "Feiticeiro": {
        1: { features: [{ name: "Origem Feiticeira", description: "A fonte do seu poder inato.", isChoice: true }, { name: "Conjuração", description: "Lance magias através da força de vontade." }], hitDice: "1d6" },
        2: { features: [{ name: "Fonte de Magia", description: "Pontos de Feitiçaria para criar espaços de magia." }] },
        3: { features: [{ name: "Metamagia (2 opções)", description: "Molde suas magias.", isChoice: true }] },
        4: { features: [ASI] },
        5: { features: [{ name: "Magias de 3º Nível", description: "Acesso a explosões de poder arcano." }] },
        6: { features: [{ name: "Recurso de Origem", description: "Habilidade de subclasse." }] },
        7: { features: [{ name: "Magias de 4º Nível", description: "Dobre a realidade ao seu redor." }] },
        8: { features: [ASI] },
        9: { features: [{ name: "Magias de 5º Nível", description: "Manifestações épicas de poder." }] },
        10: { features: [{ name: "Metamagia (3ª opção)", description: "Mais controle sobre sua magia.", isChoice: true }] },
        11: { features: [{ name: "Magias de 6º Nível", description: "Poder arcano avassalador." }] },
        12: { features: [ASI] },
        13: { features: [{ name: "Magias de 7º Nível", description: "Mestria sobre o cosmos." }] },
        14: { features: [{ name: "Recurso de Origem", description: "Poder superior da subclasse." }] },
        15: { features: [{ name: "Magias de 8º Nível", description: "Poder divino de feiticeiro." }] },
        16: { features: [ASI] },
        17: { features: [{ name: "Magias de 9º Nível", description: "Manifestação definitiva da magia." }, { name: "Metamagia (4ª opção)", description: "Domínio total sobre feitiços.", isChoice: true }] },
        18: { features: [{ name: "Recurso de Origem", description: "Mestria final da subclasse." }] },
        19: { features: [ASI] },
        20: { features: [{ name: "Restauração de Feiticeiro", description: "Recupere 4 pontos de feitiçaria em descansos curtos." }] }
    },
    "Bruxo": {
        1: { features: [{ name: "Patrono Transcendente", description: "Entidade com quem fez seu pacto.", isChoice: true }, { name: "Magia de Pacto", description: "Recupera espaços de magia em descansos CURTOS!" }], hitDice: "1d8" },
        2: { features: [{ name: "Invocações Místicas (2)", description: "Poderes extras concedidos pelo patrono.", isChoice: true }] },
        3: { features: [{ name: "Dádiva do Pacto", description: "Bênção especial (Lâmina, Tomo ou Corrente).", isChoice: true }, { name: "Magias de 2º Nível", description: "Poder de sombra aumentado." }] },
        4: { features: [ASI] },
        5: { features: [{ name: "Invocações Místicas (3)", description: "Novos segredos aprendidos.", isChoice: true }, { name: "Magias de 3º Nível", description: "Energia do patrono aumentada." }] },
        6: { features: [{ name: "Recurso de Patrono", description: "Habilidade de subclasse." }] },
        7: { features: [{ name: "Invocações Místicas (4)", description: "Segredos proibidos.", isChoice: true }, { name: "Magias de 4º Nível", description: "Manifestação de poder obscuro." }] },
        8: { features: [ASI] },
        9: { features: [{ name: "Invocações Místicas (5)", description: "Poderes ocultos.", isChoice: true }, { name: "Magias de 5º Nível", description: "O máximo da Magia de Pacto." }] },
        10: { features: [{ name: "Recurso de Patrono", description: "Resiliência ou poder extra." }] },
        11: { features: [{ name: "Arcano Místico (6º Nível)", description: "Um segredo de 6º nível que pode ser usado 1/dia." }, { name: "Invocações Místicas (6)", description: "Conhecimento sombrio.", isChoice: true }] },
        12: { features: [ASI] },
        13: { features: [{ name: "Arcano Místico (7º Nível)", description: "Um segredo de 7º nível.", isChoice: true }, { name: "Invocações Místicas (7)", description: "Segredos finais.", isChoice: true }] },
        14: { features: [{ name: "Recurso de Patrono", description: "Poder final da entidade pactuada." }] },
        15: { features: [{ name: "Arcano Místico (8º Nível)", description: "Um segredo de 8º nível.", isChoice: true }, { name: "Invocações Místicas (8)", description: "O ápice das invocações.", isChoice: true }] },
        16: { features: [ASI] },
        17: { features: [{ name: "Arcano Místico (9º Nível)", description: "O segredo oculto final de 9º nível.", isChoice: true }] },
        18: { features: [{ name: "Invocações Místicas (9)", description: "Lenda viva das sombras.", isChoice: true }] },
        19: { features: [ASI] },
        20: { features: [{ name: "Mestre do Pacto", description: "Peça ao seu patrono para recuperar todos os seus espaços de magia instantaneamente (1/descanso longo)!" }] }
    },
    "Mago": {
        1: { features: [{ name: "Recuperação Arcana", description: "Recupere magias em descansos curtos." }, { name: "Conjuração", description: "Lance magias através do estudo e estudo." }], hitDice: "1d6" },
        2: { features: [{ name: "Tradição Arcana", description: "Sua escola de especialização mágica.", isChoice: true }] },
        3: { features: [{ name: "Magias de 2º Nível", description: "Segredos básicos revelados." }] },
        4: { features: [ASI] },
        5: { features: [{ name: "Magias de 3º Nível", description: "Acesso a Bolas de Fogo e mais." }] },
        6: { features: [{ name: "Recurso de Tradição", description: "Habilidade de subclasse." }] },
        7: { features: [{ name: "Magias de 4º Nível", description: "Manipule as leis da física." }] },
        8: { features: [ASI] },
        9: { features: [{ name: "Magias de 5º Nível", description: "Segredos arcanos superiores." }] },
        10: { features: [{ name: "Recurso de Tradição", description: "Habilidade avançada de escola." }] },
        11: { features: [{ name: "Magias de 6º Nível", description: "Poder de arquimago incipiente." }] },
        12: { features: [ASI] },
        13: { features: [{ name: "Magias de 7º Nível", description: "Mestria sobre o espaço-tempo." }] },
        14: { features: [{ name: "Recurso de Tradição", description: "Poder final de escola mágica." }] },
        15: { features: [{ name: "Magias de 8º Nível", description: "Segredos que desafiam a morte." }] },
        16: { features: [ASI] },
        17: { features: [{ name: "Magias de 9º Nível", description: "O ápice do conhecimento arcano." }] },
        18: { features: [{ name: "Mestria em Magia", description: "Escolha uma magia de 1º e 2º nível para lançar SEM gastar espaços!", isChoice: true }] },
        19: { features: [ASI] },
        20: { features: [{ name: "Assinatura Mágica", description: "Duas magias de 3º nível sempre preparadas e que não contam no limite!", isChoice: true }] }
    }
};

export const RACE_FEATURES: Record<string, ClassFeature[]> = {
    // ... mantido as raças anteriores ...
    "Anão": [{ name: "Visão no Escuro", description: "18m" }, { name: "Resiliência Anã", description: "Resistência a veneno." }],
    "Elfo": [{ name: "Visão no Escuro", description: "18m" }, { name: "Ancestralidade Feérica", description: "Vantagem contra encanto." }],
    "Halfling": [{ name: "Sortudo", description: "Rola novamente um 1 no d20." }, { name: "Bravura", description: "Vantagem contra medo." }],
    "Humano": [{ name: "Versatilidade", description: "+1 em todos os atributos." }],
    "Draconato": [{ name: "Arma de Sopro", description: "Ataque de energia." }, { name: "Resistência", description: "Resistência ao tipo do dragão." }],
    "Meio-Elfo": [{ name: "Visão no Escuro", description: "18m" }, { name: "Versatilidade em Perícias", description: "2 perícias extras." }],
    "Meio-Orc": [{ name: "Ameaçador", description: "Proficiência em Intimidação." }, { name: "Resistência Implacável", description: "Não cai com 0 PV (1/descanso)." }],
    "Tiefling": [{ name: "Visão no Escuro", description: "18m" }, { name: "Resistência Infernal", description: "Resistência a Fogo." }]
};
