
export const dndClasses = [
  "Artífice",
  "Bárbaro",
  "Bardo",
  "Bruxo",
  "Clérigo",
  "Druida",
  "Feiticeiro",
  "Guerreiro",
  "Ladino",
  "Mago",
  "Monge",
  "Paladino",
  "Patrulheiro",
];

export const dndRaces = [
  "Anão da Colina",
  "Anão da Montanha",
  "Elfo Alto",
  "Elfo da Floresta",
  "Elfo Sombrio (Drow)",
  "Halfling Pés Leves",
  "Halfling Robusto",
  "Humano",
  "Draconato",
  "Gnomo da Floresta",
  "Gnomo das Rochas",
  "Meio-Elfo",
  "Meio-Orc",
  "Tiefling",
  "Aasimar",
  "Firbolg",
  "Goliath",
  "Kenku",
  "Lizardfolk",
  "Tabaxi",
  "Tritão",
  "Yuan-ti Pureblood",
  "Genasi (Água)",
  "Genasi (Ar)",
  "Genasi (Fogo)",
  "Genasi (Terra)",
];
