
export interface MonsterData {
    name: string;
    hp: number;
    ac: number;
    challenge: string;
    type: string;
}

export const dndMonsters: MonsterData[] = [
    { name: "Goblin", hp: 7, ac: 15, challenge: "1/4", type: "Humanoide" },
    { name: "Orc", hp: 15, ac: 13, challenge: "1/2", type: "Humanoide" },
    { name: "Esqueleto", hp: 13, ac: 13, challenge: "1/4", type: "Morto-vivo" },
    { name: "Zumbi", hp: 22, ac: 8, challenge: "1/4", type: "Morto-vivo" },
    { name: "Lobo", hp: 11, ac: 13, challenge: "1/4", type: "Fera" },
    { name: "Urso-Coruja", hp: 59, ac: 13, challenge: "3", type: "Monstruosidade" },
    { name: "Dragão Vermelho Jovem", hp: 178, ac: 18, challenge: "10", type: "Dragão" },
    { name: "Beholder", hp: 180, ac: 18, challenge: "13", type: "Aberração" },
    { name: "Lich", hp: 135, ac: 17, challenge: "21", type: "Morto-vivo" },
    { name: "Tarrasque", hp: 676, ac: 25, challenge: "30", type: "Monstruosidade" },
    { name: "Kobold", hp: 5, ac: 12, challenge: "1/8", type: "Humanoide" },
    { name: "Bugbear", hp: 27, ac: 16, challenge: "1", type: "Humanoide" },
    { name: "Ogro", hp: 59, ac: 11, challenge: "2", type: "Gigante" },
    { name: "Troll", hp: 84, ac: 15, challenge: "5", type: "Gigante" },
    { name: "Verme do Gelo", hp: 114, ac: 18, challenge: "8", type: "Monstruosidade" },
    { name: "Mímico", hp: 58, ac: 12, challenge: "2", type: "Monstruosidade" },
    { name: "Cão Infernal", hp: 45, ac: 15, challenge: "3", type: "Fiande" },
    { name: "Gelatina Ocre", hp: 45, ac: 8, challenge: "2", type: "Limo" },
    { name: "Gárgula", hp: 52, ac: 15, challenge: "2", type: "Elemental" },
    { name: "Quimera", hp: 114, ac: 14, challenge: "6", type: "Monstruosidade" },
    { name: "Hidra", hp: 172, ac: 15, challenge: "8", type: "Monstruosidade" },
    { name: "Gigante das Colinas", hp: 105, ac: 13, challenge: "5", type: "Gigante" },
    { name: "Gigante do Fogo", hp: 162, ac: 18, challenge: "9", type: "Gigante" },
    { name: "Dragão de Ouro Adulto", hp: 256, ac: 19, challenge: "17", type: "Dragão" },
    { name: "Espectro", hp: 22, ac: 12, challenge: "1", type: "Morto-vivo" },
    { name: "Vampiro", hp: 144, ac: 16, challenge: "13", type: "Morto-vivo" },
    { name: "Mantícora", hp: 68, ac: 14, challenge: "3", type: "Monstruosidade" },
    { name: "Grifo", hp: 59, ac: 12, challenge: "2", type: "Monstruosidade" },
    { name: "Aranha Gigante", hp: 26, ac: 14, challenge: "1", type: "Fera" },
    { name: "Gamo Gigante", hp: 19, ac: 14, challenge: "2", type: "Fera" },
    { name: "Centauro", hp: 45, ac: 12, challenge: "2", type: "Monstruosidade" },
    { name: "Minotauro", hp: 76, ac: 14, challenge: "3", type: "Monstruosidade" },
    { name: "Medusa", hp: 127, ac: 15, challenge: "6", type: "Monstruosidade" },
    { name: "Dríade", hp: 22, ac: 11, challenge: "1", type: "Fada" },
    { name: "Elemental do Fogo", hp: 102, ac: 13, challenge: "5", type: "Elemental" },
    { name: "Elemental da Água", hp: 114, ac: 14, challenge: "5", type: "Elemental" },
    { name: "Elemental da Terra", hp: 126, ac: 17, challenge: "5", type: "Elemental" },
    { name: "Elemental do Ar", hp: 90, ac: 15, challenge: "5", type: "Elemental" },
    { name: "Golem de Carne", hp: 93, ac: 9, challenge: "5", type: "Constructo" },
    { name: "Golem de Pedra", hp: 178, ac: 17, challenge: "10", type: "Constructo" },
    { name: "Golem de Ferro", hp: 210, ac: 20, challenge: "16", type: "Constructo" },
    { name: "Súcubo / Íncubo", hp: 66, ac: 15, challenge: "4", type: "Fiande" },
    { name: "Abocanhador Matraqueante", hp: 67, ac: 9, challenge: "2", type: "Aberração" },
    { name: "Verme Púrpura", hp: 247, ac: 18, challenge: "15", type: "Monstruosidade" },
    { name: "Wyvern", hp: 110, ac: 13, challenge: "6", type: "Dragão" },
    { name: "Basilisco", hp: 52, ac: 15, challenge: "3", type: "Monstruosidade" },
    { name: "Ettin", hp: 85, ac: 12, challenge: "4", type: "Gigante" },
    { name: "Gnoll", hp: 22, ac: 15, challenge: "1/2", type: "Humanoide" },
    { name: "Hobgoblin", hp: 11, ac: 18, challenge: "1/2", type: "Humanoide" },
    { name: "Rakshasa", hp: 110, ac: 16, challenge: "13", type: "Fiande" },
    { name: "Sahuagin", hp: 22, ac: 12, challenge: "1/2", type: "Humanoide" },
    { name: "Sombra", hp: 16, ac: 12, challenge: "1/2", type: "Morto-vivo" },
    { name: "Aparição (Wraith)", hp: 67, ac: 13, challenge: "5", type: "Morto-vivo" },
    { name: "Banshee", hp: 58, ac: 12, challenge: "4", type: "Morto-vivo" },
    { name: "Behir", hp: 168, ac: 17, challenge: "11", type: "Monstruosidade" },
    { name: "Bulette", hp: 94, ac: 17, challenge: "5", type: "Monstruosidade" },
    { name: "Chuul", hp: 93, ac: 16, challenge: "4", type: "Aberração" },
    { name: "Duergar", hp: 26, ac: 16, challenge: "1", type: "Humanoide" },
    { name: "Fogo-fátuo", hp: 22, ac: 19, challenge: "2", type: "Morto-vivo" },
    { name: "Gigante da Tempestade", hp: 230, ac: 16, challenge: "13", type: "Gigante" },
    { name: "Gigante das Nuvens", hp: 200, ac: 14, challenge: "9", type: "Gigante" },
    { name: "Gigante de Pedra", hp: 126, ac: 17, challenge: "7", type: "Gigante" },
    { name: "Harpia", hp: 38, ac: 11, challenge: "1", type: "Monstruosidade" },
    { name: "Hipogrifo", hp: 19, ac: 11, challenge: "1", type: "Monstruosidade" },
    { name: "Montículo Errante", hp: 136, ac: 15, challenge: "5", type: "Planta" },
    { name: "Unicórnio", hp: 67, ac: 12, challenge: "5", type: "Celestial" },
    { name: "Yeti", hp: 51, ac: 12, challenge: "3", type: "Monstruosidade" },
    { name: "Xorn", hp: 73, ac: 19, challenge: "5", type: "Elemental" }
];
