
export interface MonsterData {
    name: string;
    hp: number;
    ac: number;
    challenge: string;
    type: string;
    xp: number;
}

export const dndMonsters: MonsterData[] = [
    { name: "Goblin", hp: 7, ac: 15, challenge: "1/4", type: "Humanoide", xp: 50 },
    { name: "Orc", hp: 15, ac: 13, challenge: "1/2", type: "Humanoide", xp: 100 },
    { name: "Esqueleto", hp: 13, ac: 13, challenge: "1/4", type: "Morto-vivo", xp: 50 },
    { name: "Zumbi", hp: 22, ac: 8, challenge: "1/4", type: "Morto-vivo", xp: 50 },
    { name: "Lobo", hp: 11, ac: 13, challenge: "1/4", type: "Fera", xp: 50 },
    { name: "Urso-Coruja", hp: 59, ac: 13, challenge: "3", type: "Monstruosidade", xp: 700 },
    { name: "Dragão Vermelho Jovem", hp: 178, ac: 18, challenge: "10", type: "Dragão", xp: 5900 },
    { name: "Beholder", hp: 180, ac: 18, challenge: "13", type: "Aberração", xp: 10000 },
    { name: "Lich", hp: 135, ac: 17, challenge: "21", type: "Morto-vivo", xp: 33000 },
    { name: "Tarrasque", hp: 676, ac: 25, challenge: "30", type: "Monstruosidade", xp: 155000 },
    { name: "Kobold", hp: 5, ac: 12, challenge: "1/8", type: "Humanoide", xp: 25 },
    { name: "Bugbear", hp: 27, ac: 16, challenge: "1", type: "Humanoide", xp: 200 },
    { name: "Ogro", hp: 59, ac: 11, challenge: "2", type: "Gigante", xp: 450 },
    { name: "Troll", hp: 84, ac: 15, challenge: "5", type: "Gigante", xp: 1800 },
    { name: "Verme do Gelo", hp: 114, ac: 18, challenge: "8", type: "Monstruosidade", xp: 3900 },
    { name: "Mímico", hp: 58, ac: 12, challenge: "2", type: "Monstruosidade", xp: 450 },
    { name: "Cão Infernal", hp: 45, ac: 15, challenge: "3", type: "Fiande", xp: 700 },
    { name: "Gelatina Ocre", hp: 45, ac: 8, challenge: "2", type: "Limo", xp: 450 },
    { name: "Gárgula", hp: 52, ac: 15, challenge: "2", type: "Elemental", xp: 450 },
    { name: "Quimera", hp: 114, ac: 14, challenge: "6", type: "Monstruosidade", xp: 2300 },
    { name: "Hidra", hp: 172, ac: 15, challenge: "8", type: "Monstruosidade", xp: 3900 },
    { name: "Gigante das Colinas", hp: 105, ac: 13, challenge: "5", type: "Gigante", xp: 1800 },
    { name: "Gigante do Fogo", hp: 162, ac: 18, challenge: "9", type: "Gigante", xp: 5000 },
    { name: "Dragão de Ouro Adulto", hp: 256, ac: 19, challenge: "17", type: "Dragão", xp: 18000 },
    { name: "Espectro", hp: 22, ac: 12, challenge: "1", type: "Morto-vivo", xp: 200 },
    { name: "Vampiro", hp: 144, ac: 16, challenge: "13", type: "Morto-vivo", xp: 10000 },
    { name: "Mantícora", hp: 68, ac: 14, challenge: "3", type: "Monstruosidade", xp: 700 },
    { name: "Grifo", hp: 59, ac: 12, challenge: "2", type: "Monstruosidade", xp: 450 },
    { name: "Aranha Gigante", hp: 26, ac: 14, challenge: "1", type: "Fera", xp: 200 },
    { name: "Gamo Gigante", hp: 19, ac: 14, challenge: "2", type: "Fera", xp: 450 },
    { name: "Centauro", hp: 45, ac: 12, challenge: "2", type: "Monstruosidade", xp: 450 },
    { name: "Minotauro", hp: 76, ac: 14, challenge: "3", type: "Monstruosidade", xp: 700 },
    { name: "Medusa", hp: 127, ac: 15, challenge: "6", type: "Monstruosidade", xp: 2300 },
    { name: "Dríade", hp: 22, ac: 11, challenge: "1", type: "Fada", xp: 200 },
    { name: "Elemental do Fogo", hp: 102, ac: 13, challenge: "5", type: "Elemental", xp: 1800 },
    { name: "Elemental da Água", hp: 114, ac: 14, challenge: "5", type: "Elemental", xp: 1800 },
    { name: "Elemental da Terra", hp: 126, ac: 17, challenge: "5", type: "Elemental", xp: 1800 },
    { name: "Elemental do Ar", hp: 90, ac: 15, challenge: "5", type: "Elemental", xp: 1800 },
    { name: "Golem de Carne", hp: 93, ac: 9, challenge: "5", type: "Constructo", xp: 1800 },
    { name: "Golem de Pedra", hp: 178, ac: 17, challenge: "10", type: "Constructo", xp: 5900 },
    { name: "Golem de Ferro", hp: 210, ac: 20, challenge: "16", type: "Constructo", xp: 15000 },
    { name: "Súcubo / Íncubo", hp: 66, ac: 15, challenge: "4", type: "Fiande", xp: 1100 },
    { name: "Abocanhador Matraqueante", hp: 67, ac: 9, challenge: "2", type: "Aberração", xp: 450 },
    { name: "Verme Púrpura", hp: 247, ac: 18, challenge: "15", type: "Monstruosidade", xp: 13000 },
    { name: "Wyvern", hp: 110, ac: 13, challenge: "6", type: "Dragão", xp: 2300 },
    { name: "Basilisco", hp: 52, ac: 15, challenge: "3", type: "Monstruosidade", xp: 700 },
    { name: "Ettin", hp: 85, ac: 12, challenge: "4", type: "Gigante", xp: 1100 },
    { name: "Gnoll", hp: 22, ac: 15, challenge: "1/2", type: "Humanoide", xp: 100 },
    { name: "Hobgoblin", hp: 11, ac: 18, challenge: "1/2", type: "Humanoide", xp: 100 },
    { name: "Rakshasa", hp: 110, ac: 16, challenge: "13", type: "Fiande", xp: 10000 },
    { name: "Sahuagin", hp: 22, ac: 12, challenge: "1/2", type: "Humanoide", xp: 100 },
    { name: "Sombra", hp: 16, ac: 12, challenge: "1/2", type: "Morto-vivo", xp: 100 },
    { name: "Aparição (Wraith)", hp: 67, ac: 13, challenge: "5", type: "Morto-vivo", xp: 1800 },
    { name: "Banshee", hp: 58, ac: 12, challenge: "4", type: "Morto-vivo", xp: 1100 },
    { name: "Behir", hp: 168, ac: 17, challenge: "11", type: "Monstruosidade", xp: 7200 },
    { name: "Bulette", hp: 94, ac: 17, challenge: "5", type: "Monstruosidade", xp: 1800 },
    { name: "Chuul", hp: 93, ac: 16, challenge: "4", type: "Aberração", xp: 1100 },
    { name: "Duergar", hp: 26, ac: 16, challenge: "1", type: "Humanoide", xp: 200 },
    { name: "Fogo-fátuo", hp: 22, ac: 19, challenge: "2", type: "Morto-vivo", xp: 450 },
    { name: "Gigante da Tempestade", hp: 230, ac: 16, challenge: "13", type: "Gigante", xp: 10000 },
    { name: "Gigante das Nuvens", hp: 200, ac: 14, challenge: "9", type: "Gigante", xp: 5000 },
    { name: "Gigante de Pedra", hp: 126, ac: 17, challenge: "7", type: "Gigante", xp: 2900 },
    { name: "Harpia", hp: 38, ac: 11, challenge: "1", type: "Monstruosidade", xp: 200 },
    { name: "Hipogrifo", hp: 19, ac: 11, challenge: "1", type: "Monstruosidade", xp: 200 },
    { name: "Montículo Errante", hp: 136, ac: 15, challenge: "5", type: "Planta", xp: 1800 },
    { name: "Unicórnio", hp: 67, ac: 12, challenge: "5", type: "Celestial", xp: 1800 },
    { name: "Yeti", hp: 51, ac: 12, challenge: "3", type: "Monstruosidade", xp: 700 },
    { name: "Xorn", hp: 73, ac: 19, challenge: "5", type: "Elemental", xp: 1800 }
];
