export const npcProfessions = [
  "Alfaiate",
  "Taverneiro",
  "Ferreiro",
  "Boticário",
  "Guarda da cidade",
  "Pescador",
  "Caçador",
  "Fazendeiro",
  "Padeiro",
  "Curandeiro",
  "Ladrão de rua",
  "Nobre decadente",
  "Mercador viajante",
  "Músico de taverna",
  "Bibliotecário",
  "Cartógrafo",
  "Lenhador",
  "Mineiro",
  "Estalajadeiro",
  "Cervejeiro",
  "Coureiro",
  "Joalheiro",
  "Açougueiro",
  "Coveiro",
  "Arauto",
  "Alquimista",
  "Escriba",
  "Carpinteiro",
  "Pedreiro",
  "Vendedor de cavalos",
  "Marinheiro",
  "Cozinheiro",
  "Herbalista",
  "Vendedor de peixes",
  "Armeiro",
  "Flecheiro",
  "Escultor",
  "Pintor",
  "Mendigo",
  "Batedor",
  "Guia de ermos",
  "Criador de cães",
  "Falcoeiro",
  "Vendedor de vinhos",
  "Construtor de barcos"
];

export const npcAppearances = [
  "Rosto marcado por uma cicatriz antiga.",
  "Olhos de cores diferentes, um azul e outro verde.",
  "Cabelo branco e longo, trançado com esmero.",
  "Mãos calejadas e fortes de anos de trabalho.",
  "Uma tatuagem de dragão que cobre todo o braço esquerdo.",
  "Usa um monóculo dourado, apesar de ter uma visão perfeita.",
  "Sempre está com as roupas sujas de terra e fuligem.",
  "Sorriso gentil que esconde uma tristeza profunda.",
  "Corcunda e anda com o auxílio de uma bengala de madeira escura.",
  "Extremamente alto e magro, com dedos longos e finos.",
  "Nariz adunco e quebrado várias vezes.",
  "Barba ruiva e espessa, cheia de restos de comida.",
  "Olhar vazio e distante, como se estivesse em outro lugar.",
  "Careca e com a cabeça cheia de símbolos estranhos tatuados.",
  "Usa um tapa-olho de couro preto.",
  "Dentes de ouro que brilham ao sorrir.",
  "Pele pálida e doentia.",
  "Bochechas rosadas e um ar de saúde contagiante.",
  "Anda com um passo saltitante e cantarola baixo.",
  "Manca de uma perna, resultado de um ferimento de guerra.",
  "Tem um tique nervoso, piscando o olho esquerdo constantemente.",
  "Roupas elegantes e caras, mas visivelmente gastas.",
  "Cheiro constante de ervas e poções.",
  "Voz rouca e grave, quase um sussurro.",
  "Unhas longas e sujas.",
  "Uma verruga proeminente no nariz.",
  "Cabelo oleoso e despenteado.",
  "Olhos pequenos e atentos, que não perdem nenhum detalhe.",
  "Corpo robusto e musculoso.",
  "Dedo mínimo da mão direita faltando."
];

export const npcPersonalities = [
  "Ranzinza e desconfiado de estranhos.",
  "Otimista incurável que vê o bem em tudo.",
  "Pragmático e focado apenas em lucros.",
  "Medroso e assustado com a própria sombra.",
  "Curioso e sempre fazendo perguntas inconvenientes.",
  "Orgulhoso e não admite seus erros.",
  "Generoso e disposto a ajudar quem precisa.",
  "Pessimista que sempre espera o pior.",
  "Fofoqueiro e sabe de todos os segredos da cidade.",
  "Corajoso e impulsivo, age antes de pensar.",
  "Sarcástico e com um humor ácido.",
  "Completamente louco, fala com pessoas imaginárias.",
  "Solene e fala em enigmas.",
  "Leal a seus amigos até o fim.",
  "Vingativo e guarda rancor por anos.",
  "Ambicioso e não mede esforços para subir na vida.",
  "Preguiçoso e sempre tenta encontrar o caminho mais fácil.",
  "Honesto ao extremo, incapaz de mentir.",
  "Manipulador e usa os outros para seus próprios fins.",
  "Tímido e fica vermelho ao falar com outras pessoas.",
  "Cético e não acredita em magia ou deuses.",
  "Devoto fervoroso de uma divindade.",
  "Bobo e ingênuo, fácil de enganar.",
  "Intelectual que adora exibir seu conhecimento.",
  "Cansado do mundo e de tudo.",
  "Sedutor e galanteador com todos.",
  "Paranoico, acha que todos estão conspirando contra ele.",
  "Estoico, raramente demonstra emoções.",
  "Alegre e adora uma boa festa.",
  "Melancólico e vive lamentando o passado."
];

export const npcRaces = [
  "Humano",
  "Elfo",
  "Anão",
  "Halfling",
  "Gnomo",
  "Meio-Elfo",
  "Meio-Orc",
  "Tiefling",
  "Draconato",
  "Goblin",
  "Orc",
  "Genasi"
];
