/**
 * Banco de dados de descrições de magias traduzidas para Português
 * Focado em magias fora do SRD (Xanathar, Tasha, etc)
 */

export const SPELL_DESCRIPTIONS_PT: Record<string, string> = {
    // TRUQUES

    "Booming Blade": "Você brande a arma usada na conjuração e faz um ataque corpo a corpo com ela contra uma criatura a 1,5 metro de você. Em um acerto, o alvo sofre os efeitos normais do ataque e fica envolto em energia estrondosa até o início do seu próximo turno. Se o alvo se mover voluntariamente antes disso, ele sofre imediatamente 1d8 de dano trovejante, e a magia termina.",
    "Green-Flame Blade": "Você brande a arma usada na conjuração e faz um ataque corpo a corpo com ela contra uma criatura a 1,5 metro de você. Em um acerto, o alvo sofre os efeitos normais do ataque, e fogo verde salta do alvo para uma criatura diferente de sua escolha que você possa ver a até 1,5 metro dele. A segunda criatura sofre dano de fogo igual ao seu modificador de habilidade de conjuração.",
    "Lightning Lure": "Você cria um chicote de energia elétrica que atinge uma criatura de sua escolha que você possa ver a até 4,5 metros de você. O alvo deve ser bem-sucedido em um teste de resistência de Força ou será puxado até 3 metros em linha reta em sua direção e sofrerá 1d8 de dano elétrico se estiver a até 1,5 metro de você.",
    "Mind Sliver": "Você envia uma lança desorientadora de energia psíquica na mente de uma criatura que você possa ver dentro do alcance. O alvo deve ser bem-sucedido em um teste de resistência de Inteligência ou sofrerá 1d6 de dano psíquico e subtrairá 1d4 da próxima vez que fizer um teste de resistência antes do final do seu próximo turno.",
    "Sword Burst": "Você cria um círculo momentâneo de lâminas espectrais que varrem ao seu redor. Cada criatura a até 1,5 metro de você deve ser bem-sucedida em um teste de resistência de Destreza ou sofrerá 1d6 de dano de energia.",
    "Thunderclap": "Você cria uma explosão de som trovejante que pode ser ouvida a até 30 metros de distância. Cada criatura a até 1,5 metro de você deve fazer um teste de resistência de Constituição. Em um fracasso, a criatura sofre 1d6 de dano trovejante.",
    "Toll the Dead": "Você aponta para uma criatura que possa ver dentro do alcance, e o som de um sino fúnebre doloroso preenche o ar ao redor dela por um momento. O alvo deve ser bem-sucedido em um teste de resistência de Sabedoria ou sofrerá 1d8 de dano necrótico. Se o alvo estiver com falta de algum ponto de vida, ele sofre 1d12 de dano necrótico em vez disso.",
    "Word of Radiance": "Você profere uma palavra divina, e uma radiância queimante erupciona de você. Cada criatura de sua escolha que você possa ver a até 1,5 metro de você deve ser bem-sucedida em um teste de resistência de Constituição ou sofrerá 1d6 de dano radiante.",
    "Control Flames": "Você escolhe uma chama não mágica que você possa ver a até 18 metros e que caiba num cubo de 1,5 metro. Você pode expandi-la, apagá-la, mudar sua cor ou criar formas simples nela.",
    "Create Bonfire": "Você cria uma fogueira mágica em um cubo de 1,5 metro no chão que você possa ver dentro do alcance. Qualquer criatura no espaço da fogueira quando você a conjura, ou que entre nela pela primeira vez num turno, deve fazer um teste de Destreza ou sofrer 1d8 de dano de fogo.",
    "Frostbite": "Você causa um frio entorpecente em uma criatura que você possa ver dentro do alcance. O alvo deve fazer um teste de Constituição. Se falhar, sofre 1d6 de dano de frio e tem desvantagem no próximo ataque com arma que fizer antes do fim do próximo turno dele.",
    "Gust": "Você captura o ar para criar um efeito pontual: empurrar uma criatura a 1,5m, criar um sopro forte ou um efeito sensorial inofensivo.",
    "Infestation": "Você faz com que um enxame de ácaros, pulgas e outros parasitas apareça momentaneamente em uma criatura. O alvo deve passar num teste de Constituição ou sofrer 1d6 de dano de veneno e se mover 1,5m em direção aleatória.",
    "Magic Stone": "Você toca de uma a três pedras e as imbui com magia. Você ou alguém pode arremessá-las ou usar uma funda para atacar. O ataque é mágico e causa 1d6 + mod de conjuração de dano de concussão.",
    "Mold Earth": "Você escolhe uma porção de terra solta ou pedra e pode escavá-la, movê-la, criar formas ou transformar o terreno difícil em normal (e vice-versa).",
    "Primal Savagery": "Você canaliza magia primal para fazer seus dentes ou unhas ficarem afiados. Faça um ataque corpo a corpo com magia. Se acertar, causa 1d10 de dano ácido.",
    "Shape Water": "Você manipula uma área de água: move, muda a cor, congela ou muda a opacidade.",
    "Friends": "Pela duração, você tem vantagem em todos os testes de Carisma direcionados a uma criatura de sua escolha que não seja hostil a você. Quando a magia termina, a criatura percebe que você usou magia para influenciar o humor dela e se torna hostil a você.",
    "Blade Ward": "Você estende a mão e trça um símbolo de proteção no ar. Até o final do seu próximo turno, você tem resistência contra dano de concussão, cortante e perfurante causado por ataques com armas.",
    "Thorn Whip": "Você cria um chicote longo, semelhante a uma vinha, coberto de espinhos que ataca ao seu comando. Faça um ataque corpo a corpo com magia contra uma criatura a até 9 metros. Se acertar, causa 1d6 de dano perfurante e se a criatura for Grande ou menor, você a puxa até 3 metros para perto de você.",

    // NÍVEL 1
    "Armor of Agathys": "Uma força mágica protetora envolve você, manifestando-se como uma geada espectral que cobre você e seu equipamento. Você ganha 5 pontos de vida temporários pela duração. Se uma criatura atingir você com um ataque corpo a corpo enquanto você tiver esses pontos de vida temporários, a criatura sofre 5 de dano de frio.",
    "Arms of Hadar": "Você invoca o poder de Hadar, o Faminto Sombrio. Tentáculos de energia escura erupcionam de você. Cada criatura a até 3 metros de você deve fazer um teste de resistência de Força. Em um fracasso, o alvo sofre 2d6 de dano necrótico e não pode fazer reações até o próximo turno dele. Em um sucesso, sofre metade do dano.",
    "Catapult": "Escolha um objeto pesando entre 0,5 e 2,5 kg dentro do alcance que não esteja sendo vestido ou carregado. O objeto voa em linha reta até 27 metros em uma direção que você escolher antes de cair no chão. Se o objeto atingir uma criatura, ela deve passar num teste de Destreza ou sofrer 3d8 de dano de concussão.",
    "Cause Fear": "Você desperta o senso de mortalidade em uma criatura. O alvo deve passar num teste de Sabedoria ou ficar amedrontado por você até a magia acabar.",
    "Chaos Bolt": "Você arremessa uma massa oscilante de energia caótica em uma criatura ao alcance. Faça um ataque de magia à distância. Em um acerto, o alvo sofre 2d8 + 1d6 de dano. Escolha um dos d8s; o número rolado determina o tipo de dano (ácido, frio, fogo, força, elétrico, veneno, psíquico ou trovejante). Se rolar o mesmo número nos dois d8s, a energia salta para outro alvo.",
    "Ceremony": "Você executa uma de várias cerimônias religiosas: Expiação, Abençoar Água, Maioridade, Dedicação, Rito Fúnebre ou Casamento, concedendo benefícios específicos.",
    "Chromatic Orb": "Você arremessa uma esfera de energia de 10 cm de diâmetro numa criatura. Escolha ácido, frio, fogo, elétrico, veneno ou trovejante. Se acertar o ataque, causa 3d8 de dano do tipo escolhido.",
    "Dissonant Whispers": "Você sussurra uma melodia discordante que apenas uma criatura à sua escolha pode ouvir. O alvo deve fazer um teste de Sabedoria. Se falhar, sofre 3d6 de dano psíquico e deve usar sua reação para fugir de você o mais rápido possível.",
    "Earth Tremor": "Você causa um tremor no solo num raio de 3 metros ao seu redor. Cada criatura na área deve fazer um teste de Destreza. Se falhar, sofre 1d6 de dano de concussão e cai no chão (fica caída).",
    "Ensnaring Strike": "Na próxima vez que você acertar uma criatura com um ataque de arma, uma massa de vinhas espinhosas surge no ponto de impacto. O alvo deve passar num teste de Força ou ser contido pelas vinhas e sofrer 1d6 de dano perfurante a cada turno.",
    "Hail of thorns": "Na próxima vez que acertar um ataque à distância, além do dano normal, uma chuva de espinhos explode. O alvo e criaturas a 1,5m dele devem fazer um teste de Destreza ou sofrer 1d10 de dano perfurante.",
    "Hex": "Você coloca uma maldição em uma criatura. Até a magia acabar, você causa 1d6 de dano necrótico extra ao alvo sempre que acertá-lo com um ataque. Além disso, escolha um atributo; o alvo tem desvantagem em testes de habilidade com esse atributo.",
    "Ice Knife": "Você cria uma lasca de gelo e a arremessa em uma criatura a até 18 metros. Faça um ataque de magia. Se acertar, causa 1d10 de dano perfurante. Acertando ou não, a lasca explode e todos a 1,5m devem passar num teste de Destreza ou sofrer 2d6 de dano de frio.",
    "Ray of Sickness": "Um raio de energia esverdeada chicoteia em direção a uma criatura. Faça um ataque de magia. Se acertar, causa 2d8 de dano de veneno e o alvo deve passar num teste de Constituição ou ficar envenenado até o fim do próximo turno.",
    "Silvery Barbs": "Você distrai magicamente uma criatura quando ela tem sucesso numa jogada de ataque, teste de habilidade ou resistência. A criatura deve rolar novamente e usar o menor valor. Você então escolhe outra criatura para ganhar vantagem na próxima jogada.",
    "Tasha's Caustic Brew": "Um fluxo de ácido emana de você em uma linha de 9 metros. Cada criatura na linha deve passar num teste de Destreza ou ser coberta de ácido, sofrendo 2d4 de dano ácido no início de cada um de seus turnos até que o ácido seja raspado.",
    "Tasha's Hideous Laughter": "Uma criatura à sua escolha percebe tudo como hilariante e cai na gargalhada. Ela deve passar num teste de Sabedoria ou cairá no chão e ficará incapacitada, rindo.",
    "Witch Bolt": "Um raio de energia azul crepitante se lança em direção a uma criatura. Faça um ataque de magia. Se acertar, causa 1d12 de dano elétrico e, em cada um dos seus turnos, você pode usar sua ação para causar 1d12 de dano elétrico automaticamente.",
    "Zephyr Strike": "Você se move como o vento. Você não provoca ataques de oportunidade, e uma vez antes da magia acabar, você tem vantagem em um ataque e causa 1d8 de dano de força extra.",
    "Absorb Elements": "A magia captura parte da energia recebida, diminuindo seu efeito sobre você e armazenando-a para seu próximo ataque corpo a corpo. Você tem resistência ao tipo de dano desencadeante até o início do seu próximo turno. Além disso, a primeira vez que você atingir com um ataque corpo a corpo em seu próximo turno, o alvo sofre 1d6 de dano extra do tipo desencadeante, e a magia termina.",
    "Beast Bond": "Você estabelece um elo telepático com uma besta que seja amigável ou esteja enfeitiçada por você. O elo funciona enquanto vocês estiverem na mesma linha de visão.",
    "Snare": "Você cria uma armadilha mágica invisível usando uma corda. Quando uma criatura pisa nela, deve passar num teste de Destreza ou ser içada no ar e ficar contida.",

    // NÍVEL 2
    "Aganazzar's Scorcher": "Uma linha de chamas rugidoras de 9 metros emana de você. Cada criatura na linha deve fazer um teste de Destreza, sofrendo 3d8 de dano de fogo se falhar.",
    "Beast Sense": "Você toca uma besta disposta e, pela duração, pode usar seus sentidos (ver, ouvir, cheirar) através dos sentidos dela, mantendo seus próprios sentidos desligados.",
    "Cloud of Daggers": "Você preenche o ar num cubo de 1,5 metro com adagas giratórias. Uma criatura sofre 4d4 de dano cortante quando entra na área ou começa seu turno lá.",
    "Cordon of Arrows": "Você planta 4 peças de munição no chão. Quando uma criatura chega a 9 metros, uma munição voa nela (ataque + seu mod). Causa 1d6 de dano.",
    "Crown of Madness": "Um alvo deve passar num teste de Sabedoria ou ficar enfeitiçado. A cada turno, ele deve usar sua ação para atacar uma criatura próxima que você escolher.",
    "Dragon's Breath": "Você toca uma criatura e a imbui com poder. Ela pode usar uma ação para exalar energia num cone de 4,5m, causando 3d6 de dano (ácido, frio, fogo, elétrico ou veneno).",
    "Dust Devil": "Você cria um pequeno redemoinho de poeira. Ele pode se mover, empurrar criaturas e causar dano de concussão (1d8) a quem terminar o turno perto dele.",
    "Earthbind": "Você escolhe uma criatura que pode ver. Tiras de terra amarela envolvem-na. Ela deve passar num teste de Força ou seu deslocamento de voo se torna 0 e ela é puxada para o chão.",
    "Healing Spirit": "Você invoca um espírito da natureza. Quando você ou uma criatura que você pode ver se move para o espaço do espírito ou começa o turno lá, você pode fazer o espírito curar 1d6 pontos de vida.",
    "Hold Person": "Escolha um humanoide que você possa ver dentro do alcance. O alvo deve ser bem-sucedido em um teste de resistência de Sabedoria ou ficará paralisado pela duração.",
    "Maximilian's Earthen Grasp": "Você converte o solo em uma mão de terra média. Ela tenta agarrar uma criatura (Teste de Força). Se agarrar, causa 2d6 de concussão e esmaga o alvo.",
    "Melf's Acid Arrow": "Uma flecha verde cintilante voa para o alvo. Faça um ataque de magia. Se acertar, causa 4d4 dano ácido imediato e 2d4 no fim do próximo turno. Se errar, metade do dano inicial.",
    "Mind Spike": "Você ataca a mente de uma criatura. Ela deve passar num teste de Sabedoria ou sofrer 3d8 psíquico. Você sabe a localização dela enquanto durar a magia.",
    "Misty Step": "Brevemente cercado por névoa prateada, você se teletransporta até 9 metros para um espaço desocupado que você possa ver.",
    "Nystul's Magic Aura": "Você coloca uma ilusão sobre uma criatura ou objeto para enganar magias de adivinhação, fazendo-a parecer mágica (ou não mágica) ou mudando seu tipo de criatura aparente.",
    "Phantasmal Force": "Você cria uma ilusão na mente de uma criatura. Ela acredita que é real e pode sofrer 1d6 de dano psíquico por turno se a ilusão for de algo perigoso.",
    "Pass without Trace": "Um véu de sombras e silêncio irradia de você. Você e companheiros ganham +10 em Furtividade e não deixam rastros.",
    "Shadow Blade": "Você tece fios de sombra para criar uma espada de escuridão solidificada. Ela causa 2d8 de dano psíquico e tem propriedades de acuidade e arremesso.",
    "Snilloc's Snowball Swarm": "Uma rajada de bolas de neve mágicas explode num ponto. Criaturas num raio de 1,5m sofrem 3d6 de dano de frio (teste de Destreza para metade).",
    "Spiritual Weapon": "Você cria uma arma espectral flutuante. Você pode fazer ataques corpo a corpo com ela (1d8 + mod). Ela se move com ação bônus.",
    "Suggestion": "Você sugere um curso de atividade a uma criatura que possa te ouvir. Ela deve passar num teste de Sabedoria ou seguirá a sugestão por até 8 horas.",
    "Summon Beast": "Você convoca um espírito bestial (Aéreo, Terrestre ou Aquático) que obedece seus comandos e luta por você.",
    "Tasha's Mind Whip": "Você chicoteia psicologicamente uma criatura. Ela sofre 3d6 dano psíquico e no próximo turno só pode mover, usar ação OU ação bônus (não tudo). (Inteligência anula).",
    "Warding Wind": "Um vento forte sopra ao seu redor. Ele ensurdece você e outros, cria terreno difícil, apaga chamas e dá desvantagem em ataques à distância contra você.",

    // NÍVEL 3
    "Aura of Vitality": "Uma aura curativa de 9 metros irradia de você. Com uma ação bônus, você pode fazer a aura curar 2d6 PV de uma criatura nela.",
    "Catnap": "Você faz gestos calmantes e até 3 criaturas adormecem por 10 minutos. Ao acordarem, elas ganham os benefícios de um Descanso Curto.",
    "Counterspell": "Você tenta interromper uma criatura no processo de conjuração. Se a magia for de 3º nível ou menor, ela falha.",
    "Crusader's Mantle": "Poder divino irradia de você. Aliados a até 9 metros causam +1d4 de dano radiante em seus ataques com arma.",
    "Dispel Magic": "Escolha uma criatura, objeto ou efeito mágico dentro do alcance. Qualquer magia de 3º nível ou inferior no alvo termina.",
    "Elemental Weapon": "Você toca uma arma não mágica. Ela se torna mágica, ganha +1 no ataque e causa +1d4 de dano elemental (ácido, frio, fogo, raio ou trovão).",
    "Enemies Abound": "Você confunde a mente de uma criatura. Ela vê todos como inimigos e deve atacar a criatura mais próxima aleatoriamente, seja aliado ou inimigo.",
    "Erupting Earth": "Uma fonte de terra e pedras explode num cubo de 6 metros. Criaturas sofrem 3d12 de concussão e o terreno vira difícil.",
    "Fast Friends": "Você encanta uma criatura para que ela o considere um amigo próximo e faça favores para você, desde que não sejam perigosos.",
    "Fireball": "Uma explosão de fogo preenche uma esfera de 6 metros. Criaturas falhando em Destreza sofrem 8d6 de fogo.",
    "Flame Arrows": "Você toca uma aljava contendo munição. As próximas 12 munições causam +1d6 de dano de fogo ao acertar.",
    "Fly": "Você toca uma criatura voluntária. O alvo ganha deslocamento de voo de 18 metros pela duração.",
    "Haste": "Escolha uma criatura voluntária. Até a magia acabar, o deslocamento do alvo é dobrado, ele ganha +2 na CA, tem vantagem em testes de Destreza e ganha uma ação adicional.",
    "Hunger of Hadar": "Você abre um portal para a escuridão entre as estrelas. Uma esfera de 6m de escuridão e frio (2d6) e tentáculos ácidos (2d6) surge.",
    "Hypnotic Pattern": "Você cria um padrão de cores hipnóticas que tece pelo ar. Criaturas na área que verem o padrão devem passar em Sabedoria ou ficar enfeitiçadas e incapacitadas.",
    "Intellect Fortress": "Você ou um aliado ganha resistência a dano psíquico e vantagem em testes de Inteligência, Sabedoria e Carisma.",
    "Leomund's Tiny Hut": "Uma cúpula de força imóvel de 3 metros de raio surge ao seu redor. Ela protege contra clima e impede que inimigos entrem, mas permite que você veja fora.",
    "Life Transference": "Você sacrifica sua própria saúde para curar outro. Você sofre 4d8 de dano necrótico e cura um alvo o dobro do dano sofrido.",
    "Lightning Bolt": "Um relâmpago de 30 metros de comprimento e 1,5 de largura sai de você. Criaturas na linha sofrem 8d6 dano elétrico (Dex metade).",
    "Magic Circle": "Você cria um cilindro de energia mágica de 3m de raio que protege contra (ou aprisiona) celestiais, elementais, fadas, ínferos ou mortos-vivos.",
    "Mass Healing Word": "Você profere uma palavra de restauração. Até 6 criaturas a 18m recuperam 1d4 + mod de vida.",
    "Melf's Minute Meteors": "Você cria 6 meteoros minúsculos orbitando você. Com uma ação bônus, pode lançar até dois, cada um causando 2d6 de dano de fogo em área pequena.",
    "Revivify": "Você toca uma criatura que morreu no último minuto. Ela retorna à vida com 1 ponto de vida.",
    "Sending": "Você envia uma mensagem curta de 25 palavras para qualquer criatura familiar a você, em qualquer lugar ou plano.",
    "Slow": "Você altera o tempo ao redor de até 6 criaturas. Elas ficam lentas, têm -2 na CA e Destreza, não podem usar reações e só fazem uma ação OU bônus.",
    "Spirit Guardians": "Você convoca espíritos protetores que flutuam ao seu redor. Inimigos a até 4,5m sofrem 3d8 de dano radiante ou necrótico a cada turno e têm movimento reduzido.",
    "Summon Fey": "Você convoca um espírito feérico (Alegre, Fúnebre ou Enganador) que luta ao seu lado e tem truques especiais.",
    "Summon Lesser Demons": "Você convoca demonios caóticos e hostis que atacam o alvo mais próximo (cuidado!).",
    "Summon Shadowspawn": "Você convoca uma criatura das sombras (Fúria, Desespero ou Medo) para lutar por você.",
    "Summon Undead": "Você convoca um morto-vivo (Fantasmagórico, Putrefato ou Esquelético) para servir você.",
    "Thunder Step": "Você se teletransporta 27 metros. No ponto onde você estava, uma explosão sônica causa 3d10 de dano trovejante.",
    "Tidal Wave": "Você conjura uma onda de água que cai sobre uma área, derrubando criaturas e causando 4d8 de dano de concussão.",
    "Tiny Servant": "Você toca um objeto minúsculo e ele cria braços e pernas, tornando-se um servo leal por 8 horas.",
    "Vampiric Touch": "O toque de sua mão sombria drena a força vital. Faça um ataque. Se acertar, causa 3d6 necrótico e você cura metade do dano.",
    "Wall of Sand": "Você cria uma parede de areia rodopiante que bloqueia visão e custa movimento extra para atravessar.",
    "Wall of Water": "Você cria uma parede de água que reduz dano de ataques à distância e pode congelar se sofrer dano de frio.",

    // NÍVEL 4
    "Arcane Eye": "Você cria um olho mágico invisível que flutua pelo ar, permitindo ver remotamente com visão no escuro.",
    "Banishment": "Você tenta enviar uma criatura para outro plano de existência. Se ela falhar em Carisma, é banida.",
    "Blight": "Energia necromântica drena a umidade de uma criatura. Causa 8d8 de dano necrótico. Plantas sofrem máximo e desvantagem.",
    "Charm Monster": "Você tenta enfeitiçar uma criatura (não apenas humanoide). Ela deve passar em Sabedoria ou te ver como amigo.",
    "Confusion": "Você assalta a mente de criaturas numa esfera de 3m. Elas agem aleatoriamente, atacando o nada ou fugindo.",
    "Conjure Woodland Beings": "Você convoca criaturas feéricas (como dríades ou pixies) para ajudá-lo.",
    "Death Ward": "Você toca uma criatura. A primeira vez que ela cairia a 0 PV, ela cai a 1 PV. Também protege contra morte instantânea.",
    "Dimension Door": "Você se teletransporta, levando até 1 passageiro, para qualquer lugar a até 150 metros.",
    "Divination": "Você faz uma oferenda e uma entidade ou deus revela um presságio verdadeiro sobre um evento futuro.",
    "Elemental Bane": "Você sobrecarrega uma criatura com energia elemental. Ela perde resistência ao elemento escolhido e sofre +2d6 de dano desse tipo.",
    "Evard's Black Tentacles": "Tentáculos negros e grossos preenchem uma área de 6m. O terreno é difícil e quem entrar pode ser agarrado e sofrer 3d6 de concussão.",
    "Fabricate": "Você converte matérias-primas em produtos acabados (pontes, roupas, armas) rapidamente.",
    "Find Greater Steed": "Como 'Encontrar Montaria', mas você pode invocar grifos, pégasos e outras criaturas mágicas poderosas.",
    "Greater Invisibility": "Você ou uma criatura tocada ficam invisíveis. A invisibilidade NÃO termina se atacar ou lançar magia.",
    "Guardian of Faith": "Um guardião espectral vigia uma área por 8 horas, causando 20 de dano radiante a inimigos hostis que se aproximem.",
    "Ice Storm": "Granizo de rocha e gelo cai num cilindro de 6m de raio. Causa 2d8 concussão + 4d6 frio.",
    "Mordenkainen's Faithful Hound": "Um cão fantasma invisível vigia um local. Ele late para intrusos e morde (4d8 perfurante) quem chegar perto.",
    "Mordenkainen's Private Sanctum": "Você torna uma área magicamente segura: bloqueia som, visão, teletransporte e adivinhação.",
    "Otiluke's Resilient Sphere": "Uma esfera de força cintilante envolve uma criatura, protegendo-a de tudo, mas impedindo-a de afetar o exterior.",
    "Polymorph": "Você transforma uma criatura em uma besta (como T-Rex ou Sapo). Ela assume as estatísticas da nova forma.",
    "Raulothim's Psychic Lance": "Você dispara uma lança psíquica da sua testa. Causa 7d6 de dano psíquico e incapacita o alvo (Inteligência resiste). Você pode falar o nome do alvo para não precisar vê-lo.",
    "Shadow of Moil": "Sombras semelhantes a chamas envolvem você. Você fica fortemente obscurecido, tem resistência a radiante e quem te ataca sofre 2d8 necrótico.",
    "Sickening Radiance": "Luz esverdeada e dolorosa preenche uma esfera de 9m. Criaturas sofrem 4d10 radiante e ganham 1 nível de exaustão (Con resiste).",
    "Storm Sphere": "Uma esfera de 6m de tempestade causa dano de concussão e permite que você dispare raios (4d6 elétrico) com ação bônus.",
    "Summon Aberration": "Você convoca uma aberração (Beholderkin, Slaad ou Star Spawn) para lutar, causando dano psíquico.",
    "Summon Construct": "Você convoca um golem de pedra, metal ou argila para batalhar.",
    "Summon Elemental": "Você convoca um espírito elemental materializado (Ar, Terra, Fogo, Água) para lutar.",
    "Summon Greater Demon": "Você convoca um demônio poderoso (CR 5 ou menor). Tente controlá-lo ou ele atacará todos indiscriminadamente.",
    "Vitriolic Sphere": "Uma bola de ácido esmeralda explode num raio de 6m. Causa 10d4 de dano ácido inicial + 5d4 no fim do turno.",
    "Wall of Fire": "Você cria uma parede de chamas opaca. Quem passar sofre 5d8 de dano de fogo.",
    "Watery Sphere": "Uma esfera de água de 1,5m captura e engolfa criaturas, restringindo seus movimentos.",

    // NÍVEL 5
    "Animate Objects": "Objetos inanimados ganham vida e atacam seus inimigos. Ótimo para moedas, adagas ou mesas.",
    "Bigby's Hand": "Uma mão gigante de força aparece. Ela pode socar, empurrar, agarrar ou proteger você.",
    "Circle of Power": "Uma aura de 9m protege aliados, dando vantagem em testes de resistência e evasão contra magias.",
    "Cloudkill": "Uma névoa verde e venenosa rola pelo chão, causando 5d8 de dano de veneno.",
    "Cone of Cold": "Uma rajada de ar extremamente frio sai de suas mãos em cone, causando 8d8 de dano de frio.",
    "Conjure Volley": "Você dispara uma munição que se multiplica em centenas, atingindo uma área de 12 metros de raio por 8d8 de dano.",
    "Control Winds": "Você controla a intensidade e direção do vento numa grande área, dificultando voo e movimento.",
    "Danse Macabre": "Você anima até 5 cadáveres pequenos ou médios, que se levantam como mortos-vivos sob seu controle (com bônus).",
    "Dawn": "Um cilindro de luz solar brilha, causando 4d10 de dano radiante a quem estiver nele. Ótimo contra vampiros.",
    "Destructive Wave": "Você golpeia o chão, criando uma onda de energia. Inimigos num raio de 9m sofrem 10d6 de dano e caem no chão.",
    "Dominate Person": "Você controla telepaticamente os movimentos e ações de um humanoide.",
    "Dream": "Você invade os sonhos de uma criatura para conversar ou causar pesadelos terríveis (3d6 dano psíquico ao acordar).",
    "Enervation": "Um tentáculo de tinta preta drena a vida de um alvo (4d8 necrótico) e cura você.",
    "Far Step": "Pela duração, você pode se teletransportar 18 metros como uma ação bônus a cada turno.",
    "Flame Strike": "Uma coluna divina de fogo e energia radiante desce dos céus, causando 4d6 de fogo e 4d6 radiante.",
    "Greater Restoration": "Remove efeitos debilitantes severos: petrificação, maldições, redução de atributo ou de PV máximo.",
    "Hold Monster": "Como 'Imobilizar Pessoa', mas funciona em qualquer criatura.",
    "Holy Weapon": "Você imbui uma arma com poder sagrado. Ela emite luz e causa +2d8 de dano radiante por acerto.",
    "Immolation": "Chamas intensas consomem um alvo, causando 8d6 de dano de fogo inicial e mais a cada turno, transformando-o em cinzas.",
    "Infernal Calling": "Você convoca um diabo (não demônio) para negociar ou lutar. Diabos são mais espertos e perigosos.",
    "Mass Cure Wounds": "Uma onda de energia curativa sai de você, curando 3d8 + mod em até 6 criaturas.",
    "Negative Energy Flood": "Você inunda uma área com energia negativa. Pode curar mortos-vivos ou causar muito dano necrótico e reanimar zumbis.",
    "Raise Dead": "Retorna à vida uma criatura morta há até 10 dias.",
    "Rary's Telepathic Bond": "Você cria um link telepático entre até 8 criaturas voluntárias. Elas podem conversar mentalmente.",
    "Skill Empowerment": "Você toca uma criatura e dá a ela Especialização (dobro de proficiência) em uma perícia.",
    "Steel Wind Strike": "Você desaparece e golpeia até 5 criaturas num piscar de olhos, causando 6d10 de dano de força em cada.",
    "Swift Quiver": "Você transmuta sua aljava para que ela produza munição infinita. Você pode usar uma ação bônus para fazer dois ataques com uma arma que use munição. Se a arma tiver a propriedade de carregar, ela é ignorada.",
    "Summon Celestial": "Você convoca um anjo ou espírito celestial (Vingador ou Defensor) para auxiliar.",
    "Summon Draconic Spirit": "Você convoca um dragão espiritual (Cromático, Metálico ou Gema) que tem sopro e resistência.",
    "Synaptic Static": "Uma explosão psíquica em 6m de raio causa 8d6 de dano e deixa os sobreviventes com 'cérebro nublado' (-1d6 nos ataques).",
    "Telekinesis": "Você move criaturas ou objetos pesados com a mente.",
    "Transmute Rock": "Você transforma pedra em lama (aprisionando) ou lama em pedra (prendendo pés).",
    "Wall of Force": "Uma parede invisível e indestrutível bloqueia tudo. Nada físico ou mágico passa.",
    "Wall of Light": "Uma parede de luz sólida bloqueia visão e queima quem toca (4d8 radiante). Você pode disparar raios dela.",
    "Wrath of Nature": "Árvores, pedras e grama numa área ganham vida para atacar e prender seus inimigos.",

    // NÍVEL 6
    "Arcane Gate": "Você cria dois portais interligados que permitem teletransporte rápido entre pontos visíveis.",
    "Blade Barrier": "Um muro de lâminas giratórias extremamente afiadas fornece cobertura e causa 6d10 de dano cortante.",
    "Bones of the Earth": "Seis pilares de pedra brotam do chão violentamente, levantando ou esmagando criaturas.",
    "Chain Lightning": "Um arco elétrico atinge um alvo e salta para outros três, causando 10d8 de dano elétrico.",
    "Disintegrate": "Um raio verde reduz o alvo a pó se chegar a 0 PV, causando 10d6+40 de dano de força.",
    "Druid Grove": "Você protege um bosque com neblina, árvores animadas e guardiões espectrais.",
    "Globe of Invulnerability": "Uma esfera bloqueia todas as magias de nível 5 ou menor, protegendo quem estiver dentro.",
    "Gravity Fissure": "Uma fenda no espaço-tempo atrai criaturas e causa 8d8 de dano de força.",
    "Harm": "Você libera uma doença virulenta que causa 14d6 de dano necrótico e reduz o PV máximo.",
    "Heal": "Uma onda de energia positiva cura 70 PV e remove cegueira, surdez e doenças.",
    "Heroes' Feast": "Um banquete mágico que cura doenças, dá imunidade a veneno e medo e aumenta PV máximo.",
    "Investiture of Flame": "Você se torna um avatar de fogo: imune a fogo, aura de calor e lança chamas.",
    "Investiture of Ice": "Você se torna um avatar de gelo: imune a frio, aura congelante e lança raios de gelo.",
    "Investiture of Stone": "Você se torna um avatar de terra: resistência a dano físico, move-se pela terra e derruba inimigos.",
    "Investiture of Wind": "Você se torna um avatar de vento: voo, ataques à distância falham contra você e empurra inimigos.",
    "Mass Suggestion": "Você sugere um curso de ação para até 12 criaturas, durando 24 horas sem concentração.",
    "Mental Prison": "Você prende a mente de uma criatura numa ilusão de perigo. Se ela tentar sair, sofre muito dano psíquico.",
    "Primordial Ward": "Você ganha resistência a ácido, frio, fogo, elétrico e trovão. Pode usar reação para ficar imune.",
    "Scatter": "Você teletransporta até 5 criaturas para outros lugares que você pode ver a até 36m.",
    "Soul Cage": "Você captura a alma de um humanoide recém-morto numa gaiola e pode explorá-la para curar-se ou fazer perguntas.",
    "Sunbeam": "Um feixe de luz solar brilhante causa 6d8 radiante e cega criaturas em uma linha a cada turno.",
    "Tasha's Otherworldly Guise": "Você transforma a si mesmo, ganhando asas, imunidades e usando seu atributo de conjuração para bater com armas.",
    "Tenser's Transformation": "Você se torna uma máquina de guerra: ganha 50 PV temp, armadura e armas marciais, ataque extra e vantagem.",
    "True Seeing": "Você vê tudo como realmente é: através de ilusões, invisibilidade, escuridão mágica e metamorfos.",
    "Word of Recall": "Você teleporta a si e aliados para um santuário previamente marcado em seu templo.",

    // NÍVEL 7
    "Crown of Stars": "Sete orbes estelares giram ao seu redor. Com ação bônus, você dispara um por 4d12 de dano radiante.",
    "Draconic Transformation": "Você ganha asas de dragão, visão às cegas e um sopro de energia de 6d8 com ação bônus.",
    "Dream of the Blue Veil": "Você e seus amigos dormem e são transportados para outro mundo do multiverso D&D.",
    "Etherealness": "Você entra no Plano Etéreo, tornando-se fantasmagórico e podendo atravessar paredes.",
    "Finger of Death": "Energia negativa rasga o alvo. Causa 7d8+30. Se matar humanoide, vira zumbi sob seu comando.",
    "Fire Storm": "Chamas rugidoras preenchem uma área imensa (você escolhe o formato), causando 7d10 de fogo.",
    "Forcecage": "Uma prisão de força invisível e inescapável prende uma criatura por 1 hora.",
    "Mirage Arcane": "Você altera a aparência e tato do terreno por quilômetros, podendo criar estruturas ilusórias que parecem reais.",
    "Mordenkainen's Magnificent Mansion": "Você conjura uma porta para uma mansão extradimensional luxuosa com servos invisíveis e muita comida.",
    "Mordenkainen's Sword": "Uma espada de força ataca inimigos causando 3d10 de dano.",
    "Plane Shift": "Você transporta a si e outros para um plano de existência diferente.",
    "Power Word Pain": "Você fala uma palavra que causa dor excruciante. O alvo fica com deslocamento baixo e desvantagem em tudo.",
    "Prismatic Spray": "Um cone de 8 cores diferentes atinge criaturas, cada cor com um efeito (fogo, ácido, pedra, banimento, etc).",
    "Project Image": "Você cria uma cópia ilusória de si mesmo a km de distância e pode ver/falar através dela.",
    "Regenerate": "O alvo recupera 4d8+15 PV e membros decepados crescem de volta em 2 minutos.",
    "Resurrection": "Ressuscita alguém morto há até 100 anos.",
    "Reverse Gravity": "A gravidade se inverte numa área. Criaturas caem para cima e ficam presas no teto.",
    "Symbol": "Você inscreve um glifo perigoso (Morte, Insanidade, Sono) que ativa quando alguém mexe nele.",
    "Teleport": "Transporte instantâneo para qualquer lugar no mesmo plano.",
    "Temple of the Gods": "Você cria um templo sagrado e protegido magicamente.",
    "Whirlwind": "Um tornado violento de 9m de altura suga criaturas e objetos, causando dano e restringindo movimento.",

    // NÍVEL 8
    "Abi-Dalzim's Horrid Wilting": "Você drena a umidade de todas as criaturas num cubo de 9m. Causa 12d8 de dano necrótico. Brutal contra plantas.",
    "Animal Shapes": "Você transforma todos os aliados em bestas grandes (como Mamutes ou T-Rexes) por 24h.",
    "Antimagic Field": "Uma esfera de 3m anula toda magia dentro dela. Itens, feitiços e efeitos mágicos param de funcionar.",
    "Clone": "Você cria um clone inerte. Se você morrer, sua alma vai para o clone e você vive novamente.",
    "Control Weather": "Você muda o clima (sol, chuva, tempestade) num raio de 8km.",
    "Dark Star": "Você cria uma esfera de escuridão esmagadora que causa 8d10 de dano e desintegra quem morre.",
    "Demiplane": "Você abre uma porta para uma sala vazia em um semiplano. Útitel para guardar coisas ou prisioneiros.",
    "Dominate Monster": "Você controla mentalmente qualquer criatura.",
    "Earthquake": "Tremores abrem fendas no chão, derrubam estruturas e dificultam concentração.",
    "Feeblemind": "Você esmaga o intelecto de um alvo, reduzindo Int e Car para 1. Ele vira um animal irracional.",
    "Glibness": "Sua fala se torna magicamente convincente. Você tira mínimo 15 no dado em testes de Carisma.",
    "Holy Aura": "Luz divina protege aliados (Vantagem em testes, inimigos têm Desvantagem para atacar).",
    "Illusory Dragon": "Você cria uma ilusão aterrorizante de dragão que solta um sopro real de energia.",
    "Incendiary Cloud": "Uma nuvem de fumaça e brasas quentes causa 10d8 de dano de fogo.",
    "Maddening Darkness": "Escuridão mágica preenche uma área. Quem começar o turno lá sofre dano psíquico e ouve gritos enlouquecedores.",
    "Maze": "Você bane uma criatura para um labirinto extradimensional. Ela precisa de inteligência para escapar.",
    "Mind Blank": "Protege totalmente a mente contra leitura, dano psíquico e encantamentos por 24h.",
    "Power Word Stun": "Uma palavra deixa uma criatura com menos de 150 PV atordoada.",
    "Reality Break": "Você quebra a realidade ao redor de um alvo, fazendo diferentes versões dele sofrerem efeitos variados.",
    "Sunburst": "Uma explosão de luz solar cega e queima criaturas numa área enorme.",
    "Telepathy": "Você cria um link telepático permanente com uma criatura.",
    "Tsunami": "Uma parede de água de 90 metros de altura devasta tudo em seu caminho.",

    // NÍVEL 9
    "Astral Projection": "Você projeta seu espírito e de amigos no Plano Astral.",
    "Blade of Disaster": "Você cria uma lâmina em forma de fenda na realidade. Causa 4d12 de dano de força (crítico no 18-20 caus 12d12).",
    "Foresight": "O alvo vê o futuro imediato: tem Vantagem em TUDO e inimigos têm Desvantagem contra ele por 8h.",
    "Gate": "Abre um portal para outro plano ou convoca uma entidade específica de lá.",
    "Imprisonment": "A forma suprema de prender alguém: enterrado fundo, acorrentado, preso numa gema ou em sono eterno.",
    "Invulnerability": "Você se torna imune a todo dano por 10 minutos.",
    "Mass Heal": "Você cura 700 Pontos de Vida divididos entre criaturas que escolher.",
    "Mass Polymorph": "Você transforma até 10 criaturas em bestas (transforme o exército inimigo em sapos).",
    "Meteor Swarm": "4 meteoros caem dos céus. Explosões imensas causam 40d6 de dano total cada.",
    "Power Word Heal": "Uma criatura tocada recupera todo o HP e levanta se estiver caída.",
    "Power Word Kill": "Uma criatura com menos de 100 PV morre instantaneamente. Sem teste.",
    "Prismatic Wall": "Uma parede multicolorida que cega, queima, petrifica e bane quem tentar atravessar.",
    "Psychic Scream": "Você estoura a cabeça de inimigos (literalmente, se morrerem). Causa 14d6 psíquico e atordoa.",
    "Ravenous Void": "Você cria um buraco negro gravitacional que suga tudo e destrói o terreno.",
    "Shapechange": "Você se transforma em qualquer criatura (Dragão, Demônio, Anjo) e mantém sua classe.",
    "Storm of Vengeance": "Você cria uma tempestade apocalíptica: ácido, raios, granizo e gelo caem sobre seus inimigos.",
    "Time Stop": "Você para o tempo por 1d4+1 turnos para agir livremente.",
    "True Polymorph": "Transforma criatura em criatura, objeto em criatura ou criatura em objeto. Pode ser permanente.",
    "True Resurrection": "Ressuscita qualquer um, mesmo sem corpo, e cura todas as maldições.",
    "Weird": "Ilusões dos piores medos de cada inimigo os matam de pavor (4d10 psíquico).",
    "Wish": "A magia mais poderosa. Altera a realidade, duplica magias ou realiza desejos (com riscos)."
};
